### PR TITLE
Added V8_COMPILE_CACHE_CACHE_DIR option

### PR DESCRIPTION
**Pull request by stelund**
To solve #16

### CODE REVIEW

**Comment by stelund** [comment]
@zertosh I tried to adapt to the comments you made to the previous PR for this issue. Any comments?

**Comment by aminya** [comment]
@zertosh Could you review this?

**Comment by zertosh** [comment]
Yeah sorry, I'll get to this over the next few days

**Comment by zertosh** [comment]
Published as v8-compile-cache@2.2.0

**Pull request closed without merging**
